.Dd October 27, 2022
.Dt HEAR 1
.Os Darwin
.Sh NAME
.Nm hear
.Nd macOS speech recognition via the command line
.Sh SYNOPSIS
.Nm
.Op Fl hvdms
.Op Fl i Ar audio_file
.Op Fl l Ar language
.Sh DESCRIPTION
.Nm
is a command line interface for the built-in speech recognition
capabilities in macOS. It supports transcription of both audio files
and microphone input. If no input is provided, the default behaviour
is to transcribe from the default audio input device, typically the
microphone.
.Pp
The following flags are supported:
.Bl -tag -width -indent
.It Fl s -supported
Print list of supported languages (locales) for speech recognition.
.It Fl l -language Ar lang
Specify speech recognition language (locale). Default is 'en-US'.
.It Fl i -input Ar audio_file
Input audio file. All formats supported by CoreAudio should work (e.g. WAV, MP3,
AAC, CAF, AIFF, ALAC, etc.).
.It Fl d -device
Only use on-device offline speech recognition. The default is to use whatever
the macOS Speech Recognition API thinks is best, which may include sending data
to Apple servers. When on-device is not enabled, there may be a hard limit to
the length of audio that can be transcribed in a single session. As of writing
(2022) this is about 500 characters or so.
.It Fl m -mode
Enable single-line output mode (only applies when the input is default audio
input device, e.g. microphone).
.It Fl h -help
Print help and exit.
.It Fl v -version
Print program name and version, and exit.
.El
.Pp
Returns 0 on success and greater than 0 on error or failure.
.Sh SEE ALSO
.Xr say 1
.Sh AUTHORS
.An Sveinbjorn Thordarson <sveinbjorn@sveinbjorn.org>
