.Dd March 7, 2022
.Dt HEAR 1
.Os Darwin
.Sh NAME
.Nm hear
.Nd macOS speech recognition via the command line
.Sh SYNOPSIS
.Nm
.Op Fl hvdms
.Op Fl i Ar audio_file
.Op Fl l Ar language
.Op Fl f Ar audio_fmt
.Sh DESCRIPTION
.Nm
is a command line interface for the built-in speech recognition
capabilities in macOS. It supports transcription of both audio files
and microphone input. If no input is provided, the default behaviour
is to transcribe audio from the default input device, typically
the microphone.
.Pp
The following flags are supported:
.Bl -tag -width -indent
.It Fl s -supported
Print list of supported languages (locales) for speech recognition.
.It Fl l -language Ar lang
Specify speech recognition language (locale). Default is 'en-US'.
.It Fl i -input Ar audio_file
Input audio file. All formats supported by CoreAudio should work (e.g. WAV, MP3,
AAC, CAF, AIFF, etc.). If the argument is '-', the audio data is read
from standard input, in which case you need to specify the format.
.It Fl f -format Ar format_name
Specify the format of the audio file (e.g. wav, mp3, aac, etc.). This flag
is only required when reading audio data from standard input and is
otherwise ignored.
.It Fl d -device
Only use on-device offline speech recognition. The default is to use whatever
the macOS Speech Recognition API thinks is best, which may include sending data
to Apple servers. When on-device is not enabled, there may be a hard limit to
the length of audio that can be transcribed in a single session.
.It Fl m -mode
Enable single-line output mode (only applies when the input is microphone audio).
.It Fl h -help
Print help and exit.
.It Fl v -version
Print program name and version, and exit.
.El
.Pp
Returns 0 on success and greater than 0 on error or failure.
.Sh SEE ALSO
.Xr say 1
.Sh AUTHORS
.An Sveinbjorn Thordarson <sveinbjorn@sveinbjorn.org>
