name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and test on macOS
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install xcpretty
        run: |
          gem install xcpretty
      - name: Build program
        run: |
          make build_unsigned | xcpretty -c && exit ${PIPESTATUS[0]}
      - name: Run tests
        run: |
          make runtests
      - name: Install shellcheck
        run: |
          HOMEBREW_NO_AUTO_UPDATE=1 brew install shellcheck
      - name: Run shellcheck
        run: |
          shellcheck *.sh
          shellcheck man/*.sh
